FROM linarotechnologies/alpine:edge-arm64

MAINTAINER Tyler Baker <forcedinductionz@gmail.com>

RUN apk add --no-cache bash hostapd iptables dhcp docker iproute2 iw
RUN echo "" > /var/lib/dhcp/dhcpd.leases
ADD wlanstart.sh /bin/wlanstart.sh

ENTRYPOINT [ "/bin/wlanstart.sh" ]
